SET foreign_key_checks=0;

INSERT INTO CUSTOMER(CUSTOMER_INDEX, CUSTOMER_ID, NAME, PHONE_NUMBER, EMAIL, ADDRESS, CITY, STATE, COUNTRY, ZIP)
VALUES (0,10001,"Pablo Picasso","+34636176382","-","Paseo de la Chopera, 14","-","Madrid", "Spain", "28045");
INSERT INTO CUSTOMER(CUSTOMER_INDEX, CUSTOMER_ID, NAME, PHONE_NUMBER, EMAIL, ADDRESS, CITY, STATE, COUNTRY, ZIP)
VALUES(1,20001,"Hedy Lamarr","+431514442250","-","Weiglgasse 10","Viena","Vienna","Austria","1150");
INSERT INTO CUSTOMER(CUSTOMER_INDEX, CUSTOMER_ID, NAME, PHONE_NUMBER, EMAIL, ADDRESS, CITY, STATE, COUNTRY, ZIP)
VALUES(2,30001,"Katherine Johnson","+12023580000","-","300 E St SW","Washington DC","Washington","United States","20546");

INSERT INTO CAR (VIN, MANUFACTURER, MODEL, YEAR, COLOR,ID_INDEX)
VALUES ("3K096I98581DHSNUP","Volkswagen", "Tiguan", 2019, "Blue",0);
INSERT INTO CAR (VIN, MANUFACTURER, MODEL, YEAR, COLOR,ID_INDEX)
VALUES ("ZM8G7BEUQZ97IH46V","Peugeot", "Rifter", 2019, "Red",1);
INSERT INTO CAR (VIN, MANUFACTURER, MODEL, YEAR, COLOR,ID_INDEX)
VALUES ("RKXVNNIHLVVZOUB4M","Ford", "Fusion", 2018, "White",2);
INSERT INTO CAR (VIN, MANUFACTURER, MODEL, YEAR, COLOR,ID_INDEX)
VALUES ("HKNDGS7CU31E9Z7JW","Toyota", "RAV4", 2018, "Silver",3);
INSERT INTO CAR (VIN, MANUFACTURER, MODEL, YEAR, COLOR,ID_INDEX)
VALUES ("DAM41UDN3CHU2WVF6","Volvo", "V60", 2019, "Gray",4);
INSERT INTO CAR (VIN, MANUFACTURER, MODEL, YEAR, COLOR,ID_INDEX)
VALUES ("DAM41UDN3CHU2WVF6","Volvo", "V60 Cross Country" , 2019, "Gray",5);

INSERT INTO SALESPERSON (STAFF_INDEX,STAFF_ID, NAME, STORE)
VALUES (0,00001,"Petey Cruiser","Madrid");
INSERT INTO SALESPERSON (STAFF_INDEX,STAFF_ID, NAME, STORE)
VALUES (1,00002,"Anna Sthesia","Barcelona");
INSERT INTO SALESPERSON (STAFF_INDEX,STAFF_ID, NAME, STORE)
VALUES (2,00003,"Paul Molive","Berlin");
INSERT INTO SALESPERSON (STAFF_INDEX,STAFF_ID, NAME, STORE)
VALUES (3,00004,"Gail Forcewind","Paris");
INSERT INTO SALESPERSON (STAFF_INDEX,STAFF_ID, NAME, STORE)
VALUES (4,00005,"Paige Turner","Mimia");
INSERT INTO SALESPERSON (STAFF_INDEX,STAFF_ID, NAME, STORE)
VALUES (5,00006,"Bob Frapples","Mexico City");
INSERT INTO SALESPERSON (STAFF_INDEX,STAFF_ID, NAME, STORE)
VALUES (6,00007,"Walter Melon","Amsterdam");
INSERT INTO SALESPERSON (STAFF_INDEX,STAFF_ID, NAME, STORE)
VALUES (7,00008,"Shonda Leer","São Paulo");

INSERT INTO INVOICE(INVOICE_ID, DATE, CAR_ID_INDEX, CUSTOMER_CUSTOMER_INDEX, SALESPERSON_STAFF_INDEX)
VALUES(0, 852399038, 2018-08-22, 0, 1,3);
INSERT INTO INVOICE(INVOICE_ID, DATE, CAR_ID_INDEX, CUSTOMER_CUSTOMER_INDEX, SALESPERSON_STAFF_INDEX)
VALUES(1, 731166526, 2018-12-31, 3, 0,5);
INSERT INTO INVOICE(INVOICE_ID, DATE, CAR_ID_INDEX, CUSTOMER_CUSTOMER_INDEX, SALESPERSON_STAFF_INDEX)
VALUES(2, 271135104, 2019-01-22, 2, 2,7);

INSERT INTO INVOICE(INVOICE_ID, INVOICE_NUMBER, DATE, CAR_ID_INDEX, CUSTOMER_CUSTOMER_INDEX, SALESPERSON_STAFF_INDEX)
VALUES(0, 852399038, "2018-08-22", 0, 1,3);
INSERT INTO INVOICE(INVOICE_ID, INVOICE_NUMBER,DATE, CAR_ID_INDEX, CUSTOMER_CUSTOMER_INDEX, SALESPERSON_STAFF_INDEX)
VALUES(1, 731166526, "2018-12-31", 3, 0,5);
INSERT INTO INVOICE(INVOICE_ID,INVOICE_NUMBER, DATE, CAR_ID_INDEX, CUSTOMER_CUSTOMER_INDEX, SALESPERSON_STAFF_INDEX)
VALUES(2, 271135104, "2019-01-22", 2, 2,7);
