SET foreign_key_checks = 0;

INSERT INTO Cars (Manufacter,Model,year,Color,VIN,CarID)
VALUES('Volkswagen','Tiguan',2019,'Blue','3VINVINK096I98581DHSNUP',0);
INSERT INTO Cars (Manufacter,Model,year,Color,VIN,CarID)
VALUES ('Peugeot','Rifter',2019,'Red','ZM8G7BEUQZ97IH46V',1);
INSERT INTO Cars(Manufacter,Model,year,Color,VIN,CarID)
VALUES ('Ford','Fusion',2018,'White','RKXVNNIHLVVZOUB4M',2);
INSERT INTO Cars(Manufacter,Model,year,Color,VIN,CarID)
VALUES ('Toyota','RAV4',2018,'Silver','HKNDGS7CU31E9Z7JW',3);
INSERT INTO Cars(Manufacter,Model,year,Color,VIN,CarID)
VALUES ('Volvo','V60',2019,'Gray','DAM41UDN3CHU2WVF6',4);
INSERT INTO Cars(Manufacter,Model,year,Color,VIN,CarID)
VALUES ('Volvo','V60 Cross Country','2019','Gray','DAM41UDN3CHU2WVF6',5);


INSERT INTO CUSTOMERS (CUSTOMERID,NAME, PHONENUMBER,EMAIL,ADRESS,CITY,STATEPROVINCE,COUNTRY,CUSTOMERZIP)
VALUES (10001,"Pablo Picasso","+34 636 17 63 82",'-',"Paseo de la Chopera 14",'Madrid','Madrid','Spain',28045);
INSERT INTO CUSTOMERS (CUSTOMERID,NAME, PHONENUMBER,EMAIL,ADRESS,CITY,STATEPROVINCE,COUNTRY,CUSTOMERZIP)
VALUES (20001,'Hedy Lamarr','+43 1 514442250','-','Weiglgasse 10','Viena','Vienna','Austria',1150);
INSERT INTO CUSTOMERS (CUSTOMERID,NAME, PHONENUMBER,EMAIL,ADRESS,CITY,STATEPROVINCE,COUNTRY,CUSTOMERZIP)
VALUES (30001,'Katherine Johnson','+1 202 358 0000','-','300 E St SW','Washington DC','Washington','United States',20546)
        


INSERT INTO SALESPERSONS (STAFFID, NAME, STORE)
VALUES (00001,"Petey Cruiser","Madrid");
INSERT INTO SALESPERSONS(STAFFID, NAME, STORE)
VALUES (00002,"Anna Sthesia","Barcelona");
INSERT INTO SALESPERSONS (STAFFID, NAME, STORE)
VALUES (00003,"Paul Molive","Berlin");
INSERT INTO SALESPERSONS (STAFFID, NAME, STORE)
VALUES (00004,"Gail Forcewind","Paris");
INSERT INTO SALESPERSONS (STAFFID, NAME, STORE)
VALUES (00005,"Paige Turner","Mimia");
INSERT INTO SALESPERSONS (STAFFID, NAME, STORE)
VALUES (00006,"Bob Frapples","Mexico City");
INSERT INTO SALESPERSONS (STAFFID, NAME, STORE)
VALUES (00007,"Walter Melon","Amsterdam");
INSERT INTO SALESPERSONS(STAFFID, NAME, STORE)
VALUES (00008,"Shonda Leer","São Paulo");

INSERT INTO INVOICES (INVOICEID,INVOICENUMBER,DATE,CARS_CARID,CUSTOMERS_CUSTOMERID,SALESPERSONS_STAFFID)
VALUES (0,852399038,'22-08-2018',0,1,3);
INSERT INTO INVOICES (INVOICEID,INVOICENUMBER,DATE,CARS_CARID,CUSTOMERS_CUSTOMERID,SALESPERSONS_STAFFID)
VALUES (1,731166526	,'31-12-2018',3,0,5);
INSERT INTO INVOICES (INVOICEID,INVOICENUMBER,DATE,CARS_CARID,CUSTOMERS_CUSTOMERID,SALESPERSONS_STAFFID)
VALUES (2,271135104,'22-01-2019',2,2,7);

